### ISSUE TITLE
How to add a vector icon

### ISSUE THREAD

**Issue by IvanAllue** [UdaySravanK/RNSwipeButton#1]
Good! I need the swipe to use an icon that will slide. This icon is obtained from react-native-vectors-icon. Is there any way to use it in this package?

**Comment by UdaySravanK** [comment]
Hi Ivan, thanks for reaching me out. I have updated the package to support your requirement.
Please pull the latest and check the below code
```
import Icon from 'react-native-vector-icons/FontAwesome';
const TwitterIcon = () => <Icon name="twitter" color="#3b5998" size={30} />;
<SwipeButton
        thumbIconBackgroundColor="#FFFFFF"
        thumbIconComponent={TwitterIcon}
        title="Slide to unlock"
      />
```

**Comment by IvanAllue** [comment]
I'm sorry it took so long, I swear I had answered, thank you very much ^^
