### ISSUE TITLE
Could not find a declaration file for module 'rn-swipe-button'

### ISSUE THREAD

**Issue by adnanshuja** [UdaySravanK/RNSwipeButton#13]
Hi, I'm getting this error after importing the package in my project. Any fixed for this?

**Comment by arelstone** [comment]
I havn't experience this. Could you please show us your code, this will make it easier to help you

**Comment by ruettenm** [comment]
This is a javascript an not a typescript module ;-)

So you have to write your own types.

Would be nice if the author could publish them in the future or simple switch to TypeScript 👍

**Comment by arelstone** [comment]
@ruettenm Could you please review my PR. See if anything is missing

**Comment by UdaySravanK** [comment]
Hi @adnanshuja, TypeScript definition is now available in the latest version. Can you please check and close this issue.

**Comment by ruettenm** [comment]
Looks good. Thanks 👍

**Comment by arelstone** [comment]
@UdaySravanK Lets close this issue

**Comment by UdaySravanK** [comment]
Fixed and verified
