### ISSUE TITLE
 SwipeThumb: Support for defaultProps will be removed from function components in a future major release

### ISSUE THREAD

**Issue by rodrigodiasf1984** [UdaySravanK/RNSwipeButton#136]
**Describe the bug**
Hi, first i'd like to thank you for this package!
I'm gettin this error warning: 

" Warning: SwipeThumb: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.
    in SwipeThumb (created by SwipeButton)"

**To Reproduce**
1. Install the package 1.3.8
2. run the project
3.look at the metro

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/a56bd4df-bd0f-4ceb-aab5-08c33a94f98d)
]

@uday-kybing does this error can break the package in the future ? Thanks

**Comment by JKKholmatov** [comment]
Same problem, any solutions?

**Comment by UdaySravanK** [comment]
Thanks for reporting. I will look into it as soon as I can.

**Comment by UdaySravanK** [comment]
https://github.com/UdaySravanK/RNSwipeButton/pull/137
Here is the PR to fix the warning. Please review it.
Since the changes are pretty simple, I will keep the PR open for just 1 day i.e. until Nov 8, 9PM EST. On Nov 9th, I will release a new version.

**Comment by UdaySravanK** [comment]
> Does this error can break the package in the future ? Thanks

Yes it may break the app if your usage is relying on the default props. But you can easily fix them by simply setting the same default props mentioned in [the source code](https://github.com/UdaySravanK/RNSwipeButton/blob/531225474f334cfb493849b9ada1ea60a592fdd6/src/components/SwipeButton/index.js#L171).

**Comment by UdaySravanK** [comment]
Fixed in v2.0.0
