### ISSUE TITLE
Ability to customised border width and shadows through props

### ISSUE THREAD

**Issue by Venkat1128** [UdaySravanK/RNSwipeButton#14]
First off great job on the swipe button. It functions really great. 

We were trying to incorporate this into our project but we found we were not able to completely customise the swipe button. We wanted to change the border width on the swipe button container but it seems to be hard coded to 1px. 

Also we were hoping to apply shadows to the thumb icon. Would this be possible to do?

Thanks,
Venkat

**Comment by UdaySravanK** [comment]
Hi @Venkat1128, I have published a new version v1.2.5 which has 2 new props
- **containerStyles**: to set styles on main container
- **thumbIconStyles**: to set styles on thumb icon container

Please check and let me, if this solves your problem. Sorry for late response.

Thanks!
Uday

**Comment by Venkat1128** [comment]
Thanks @UdaySravanK for taking the time to add props. I'll let you know once we implement this into our project.
