### ISSUE TITLE
Reverse direction swipable (Feature Request)

### ISSUE THREAD

**Issue by palakornv** [UdaySravanK/RNSwipeButton#2]
Hi,

I have used your components. It is really good!
I would like to request a feature that makes it can swipe from right to left.
It would be perfect. I can't find any that can do this.

Regards,
Palakorn V.

**Comment by UdaySravanK** [comment]
Hi @palakornv, I have added the right to left swipe feature. Please check v1.1.0. Thanks for reaching out to me.

**Comment by palakornv** [comment]
thanks, this is wonderful! :-)
