### ISSUE TITLE
thumbIconBackgroundColor

### ISSUE THREAD

**Issue by patrickgodinho** [UdaySravanK/RNSwipeButton#23]
![image](https://user-images.githubusercontent.com/4711839/78785296-4d1f6f00-797d-11ea-8b99-3507d4a71cd3.png)

![image](https://user-images.githubusercontent.com/4711839/78785317-58729a80-797d-11ea-8121-b4e672672137.png)

How to change the thumbColor?

**Comment by fatihhayri** [comment]
`thumbIconBackgroundColor="#f00"
  thumbIconBorderColor="#00f"`

**Comment by IaroslavTernovy** [comment]
Same here  `thumbIconBackgroundColor` doesn't change background color of a thumb

**Comment by arryanggaputra** [comment]
@patrickgodinho  @IaroslavTernovy  @fatihhayri you need to fill `thumbIconComponent` props.

**Comment by UdaySravanK** [comment]
@patrickgodinho This issue has been fixed in v1.3.0. Please check and close this issue. Thanks

Thanks to all for responding to this issue.
