### ISSUE TITLE
"onStartSwipe", "onStopSwip" events (New Feature Request)

### ISSUE THREAD

**Issue by palakornv** [UdaySravanK/RNSwipeButton#3]
Hi, 
I am back again. After using your new feature  "Swipe Right To Left", I would like to request some events.
1. onStartSwipe, this event will be raised when the user starts to swipe.
2. onStopSwip, this event will be raised when the user changes his mind after swiping a bit.

These two events will be very useful such as clear the text when the user starts to swipe or restore the text if the user changes his mind after swiping a bit.

Very thank you.
Palakorn V.

**Comment by UdaySravanK** [comment]
Hi @palakornv, please check the latest version v1.2.0
onStopSwipe is equal to onSwipeSuccess / onSwipeFail
Feel free to let me know if you need any other help. 

Thanks

**Comment by palakornv** [comment]
thanks a lot. Very appreciate your help.
