### ISSUE TITLE
Warning: AccessibilityInfo.fetch is deprecated

### ISSUE THREAD

**Issue by nicolasmht** [UdaySravanK/RNSwipeButton#32]
Hello, when I include RNSwipeButton, I have a react native warning saying: AccessibilityInfo.fetch is deprecated, call Accessibility.isScreenReaderEnabled instead

Thanks

**Comment by ymahnovskyy** [comment]
I've created pull request to fix this warning. #33

**Comment by UdaySravanK** [comment]
This issue has been fixed as of v1.2.9
