### ISSUE TITLE
App crashes when rendering the swipe button

### ISSUE THREAD

**Issue by mclima123** [UdaySravanK/RNSwipeButton#36]
Hi, my app crashes when using this library. I get the following error when first rendering the button:
```
Error: AnimatedValue: Attempting to set value to undefined
This error is located at:
    in SwipeThumb (at SwipeButton/index.js:148)
```

I found the solution to be quite simple. In line 24 of SwipeThumb/index.js, change
`animatedWidth: new Animated.Value(),`
to
`animatedWidth: new Animated.Value(0),`

Versions:

- react-native v0.63.0
- rn-swipe-button v1.2.8

It seems no one else is experiencing this issue, so any help would be welcome.

**Comment by blankey1337** [comment]
Can confirm, this is happening.

**Comment by palakornv** [comment]
Yes, it happens when using the latest of react-native

**Comment by blankey1337** [comment]
Looks like this will be fixed in the next release hopefully:  https://github.com/UdaySravanK/RNSwipeButton/commit/9c69ff1c86c4b3440f134431fd8156e0988176e0

@UdaySravanK can we please get a new release?

**Comment by UdaySravanK** [comment]
This issue has been fixed with PR https://github.com/UdaySravanK/RNSwipeButton/pull/30
Latest version 1.2.9 has been published. Please check and close this issue @mclima123

**Comment by AmrutaPawar025** [comment]
still issue exists with rn-swipe-button": "^1.3.8" version
