### ISSUE TITLE
EnableRightToLeftSwipe is not compatible with RTL Layout

### ISSUE THREAD

**Issue by AndrewAkram97** [UdaySravanK/RNSwipeButton#38]
I can't make the swipe gesture when I change the layout of the app to RTL layout for languages like Arabic language. it is not available, could you please help. If I kept it as default LeftToRight, I can't make the swipe as well in RTL layout.

**Comment by UdaySravanK** [comment]
Hi Andrew, Sorry about not supporting RTL layout at this moment. We have to make code changes to support this capability. I am adding this to project TODO list. I cannot give timelines but we will work on it. Thanks for reporting the requirement.

**Comment by lehoangnd** [comment]
Change EnableRightToLeftSwipe  to enableReverseSwipe
