### ISSUE TITLE
Prevent returning to initial state

### ISSUE THREAD

**Issue by oknelvapi** [UdaySravanK/RNSwipeButton#49]
Hi, folks! Could you help me, please? After successful swiping, if we press on the container, SwipeThumb always returns to the initial position. Is it possible to forbid/prevent returning to the initial position and initial width, if a user presses on the container?

**Comment by oknelvapi** [comment]
So, I've found a simple solution! I've forked this repository and I've added the `pointerEvents` prop to the `View` container inside `SwipeButton`. After that I can pass a prop like that: 
 ```javaScript
pointerEvents={swipeSuccess ? 'none' : 'auto'}  // swipeSuccess is my Boolean variable,  if response from a server has status  200, swipeSuccess will be true
````

As for me, It'll be great to add this functionality to the RNSwipeButton!

**Comment by UdaySravanK** [comment]
Hi @oknelvapi , I have added a new prop `disableResetOnTap` for your use case. Please check the latest version 1.3.4. Thanks for creating the issue.
