### ISSUE TITLE
Can't swipe button from right to left in none RTL app

### ISSUE THREAD

**Issue by viktorbk** [UdaySravanK/RNSwipeButton#52]
**Describe the bug**
I want to have the start position of swipe at the right position with "enableReverseSwipe" option.
Swiping to the left wont work only to swipe to right which is not the desired behaviour.

**Expected behavior**
You should be able to swipe to the left when starting in right position.

**Screenshots**
![image](https://user-images.githubusercontent.com/358725/101332161-38310d80-3875-11eb-8378-930ac7b0908a.png)

**Comment by UdaySravanK** [comment]
Hi @viktorbk , Can you please share your code?
Below code is from the example app and it works fine for me
```javascript
<SwipeButton
      enableReverseSwipe
      thumbIconBackgroundColor="#FFFFFF"
      thumbIconComponent={FacebookIcon}
      title="Slide to unlock"
      onSwipeSuccess={() => updateSwipeStatusMessage('Slide success!')}
    />
```

![device-2020-12-28-102717](https://user-images.githubusercontent.com/7910545/103228867-65626000-48f7-11eb-930f-10111bbef055.png)
