### ISSUE TITLE
not get installed npm i rn-swipe-button --save 

### ISSUE THREAD

**Issue by harsha-kotapati** [UdaySravanK/RNSwipeButton#55]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by harsha-kotapati** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: UserApp@0.0.1
npm ERR! Found: react@16.13.1
npm ERR! node_modules/react
npm ERR!   react@"16.13.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"16.8.6" from rn-swipe-button@1.3.3
npm ERR! node_modules/rn-swipe-button
npm ERR!   rn-swipe-button@"^1.3.2" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/fekertechnologies/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/fekertechnologies/.npm/_logs/2021-02-23T06_44_19_331Z-debug.log

**Comment by UdaySravanK** [comment]
Hi, this issue is not directly related to the `rn-swipe-button` package. Please use the latest react-native version and see if it works.
