### ISSUE TITLE
Two Position Slider Button

### ISSUE THREAD

**Issue by mick1313** [UdaySravanK/RNSwipeButton#56]
I am new to React Native having spent much of my time in Xamarin.  I have a need to use the as a Swipe to Connect feature, but also Swipe to Disconnect.  Currently the button is Single Direction, meaning when I swipe right and run onSwipeSuccess, if I click the control it resets, but what am looking for is a way to Swipe Right run onSuccess, stay there Change the arrow and text, and then when I swipe RTL run onSuccess again.  

Currently I have 2 buttons, one set to RTL.  When I swipe Right, the first button hides, and the second RTL button shows, but that presents a screen flicker.

**Comment by UdaySravanK** [comment]
Hi @mick1313 👋🏻 I understand the requirement as you want to use it pretty much like a toggle button. The motive of this component is not to so. However, you can try to find a work around solution since this component supports RTL. Please give a shot, I'm pretty confident you can get there.
