### ISSUE TITLE
How can we add custom component instead of "thumbIconComponent"

### ISSUE THREAD

**Issue by Kasheeram** [UdaySravanK/RNSwipeButton#58]
Hi,
How can we add custom component instead of "thumbIconComponent", like i want to create a rectangular button.

**Comment by UdaySravanK** [comment]
Hi @Kasheeram v1.3.5 supports your use case. Please install the latest package and try the below code

```javascript
          <SwipeButton
            containerStyles={{borderRadius: 5}}
            height={30}
            railBackgroundColor="#000000"
            railStyles={{borderRadius: 4}}
            thumbIconComponent={IntrestButton}
            thumbIconStyles={{borderRadius: 4}}
            thumbIconWidth={115} 
            title=""
          />
```

Result:
![Screen Shot 2021-07-16 at 20 56 52](https://user-images.githubusercontent.com/7910545/126021929-6675ebca-43b3-4bc0-98f8-91cb4d97f35a.png)
