### ISSUE TITLE
Ability to override font

### ISSUE THREAD

**Issue by blankey1337** [UdaySravanK/RNSwipeButton#6]
As a user, I'd like to be able to override the default font family on this component to better match my theme.

**Comment by arelstone** [comment]
I agree. This would be a nice feature. 
Gennerally I think it would be better if all styles could be passed as a prop.

**I would suggest doing something like this:**
```
thumbIcon={{
  backgroundColor: 'blue',
  borderColor: 'green'
  borderWidth: 11,
}}
titleStyle={{
  color: 'red',
  fontFamily: 'Helvetica'
}}
```

**Comment by UdaySravanK** [comment]
Hi Guys, I'm busy in supporting Target holidays. I will check this one when I get some free time. Thanks for reporting.

**Comment by UdaySravanK** [comment]
Hi @arelstone, please check the version 1.2.3
`<SwipeButton titleStyles={{fontFamily: 'Helvetica'}} />`

**Comment by arelstone** [comment]
@UdaySravanK This is awesome.. Good job <3

**Comment by blankey1337** [comment]
Thank you!
