### ISSUE TITLE
[Bug] Interface says containerStyle but correct prop is containerStyles

### ISSUE THREAD

**Issue by josera21** [UdaySravanK/RNSwipeButton#65]
**Describe the bug**
I am using Webstorm IDE and the suggestions for props for containerStyles say `containerStyle` so is kind of confusing because the correct prop is `containerStyles` 

you can see this on the file `types.d.ts`

**To Reproduce**
1. Import RNSwipeButton component
2. Try to use
3. With vscode or webstorm try to hit ctrl + space
4. You will see `containerStyle` suggestion prop

**Expected behavior**
`containerStyles` suggestions prop

**Screenshots**
![image](https://user-images.githubusercontent.com/15147964/118545383-83a0ef00-b724-11eb-9c55-7dfdaa12d287.png)

**Extra info**
 - Version 1.3.4

**Comment by UdaySravanK** [comment]
v1.3.5 addresses this issue
