### ISSUE TITLE
Need support for large font scale settings

### ISSUE THREAD

**Issue by ah584d** [UdaySravanK/RNSwipeButton#68]
**Describe the bug**
In the implementation of the lib the argument maxFontSizeMultiplier is missing from <Text/> tags, and the consequence is that when we use with large font scale the render is bad.

**To Reproduce**
1. instantiate  <SwipeButton/> in a demo code application
2. increase front scale from ios simulator (or android)
3. ![image](https://user-images.githubusercontent.com/30211873/125292537-3b203f00-e32b-11eb-94a0-c5f3df90b42a.png)
4. ![image](https://user-images.githubusercontent.com/30211873/125292597-48d5c480-e32b-11eb-8644-feb66d9c66df.png)
5. ![image](https://user-images.githubusercontent.com/30211873/125292659-55f2b380-e32b-11eb-8683-7a6fb3a26b48.png)
6. go back to your application and observe the label render

**Expected behavior**
Should add a props to limit the font size multiplier
https://reactnative.dev/docs/text#maxfontsizemultiplier

- before enlarging font scale 
 
![image](https://user-images.githubusercontent.com/30211873/125402250-dc0b0a80-e3bc-11eb-8438-7f8c8db04ff0.png)

 - this is the result after enlarging the font size
 
![image](https://user-images.githubusercontent.com/30211873/125402166-c269c300-e3bc-11eb-8d7f-842d74c78705.png)

**Desktop (please complete the following information):**
 - OS: [any]

**Comment by ah584d** [comment]
i will open a PR to fix this issue, please send me the link of the procedure to propose a solution

**Comment by UdaySravanK** [comment]
v1.3.6 addresses this issue
