### ISSUE TITLE
Ability to reset component

### ISSUE THREAD

**Issue by blankey1337** [UdaySravanK/RNSwipeButton#7]
Currently, the component gets stuck with the slider in the right-most (swiped) state. I had to manually reset it by maintaining an internal state variable which removes it from the virtual DOM on submit and then re-adds it. Feels hacky. Ideally this component might expose some helper method for resetting its internal state.

**Comment by pedropalhari** [comment]
There is a reset after fiddling with it's code.

Inside `node-modules/rn-swipe-button/source/components/SwipeThumb/index.js` on `line 147` there is a reset after a successful swipe. You can [`patch-package`](https://www.npmjs.com/package/patch-package) it for now.

**Comment by UdaySravanK** [comment]
Hi Guys, I'm busy in supporting Target holidays. I will check this one when I get some free time. Thanks for reporting.

**Comment by pedropalhari** [comment]
If you open it for me I could do a PR.

**Comment by UdaySravanK** [comment]
Sure @pedropalhari . That helps to community. Please go ahead.

**Comment by blankey1337** [comment]
Thank you, I will pull this in and let you know if there's any issues.
