### ISSUE TITLE
When I swipe, I get the warning "Can't perform a React state update on an unmounted component"

### ISSUE THREAD

**Issue by scottschindler** [UdaySravanK/RNSwipeButton#74]
**Describe the bug**
When I go to swipe, I get the following warning:

"This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function."

**Screenshots**

[Screen Shot 2021-08-04 at 11 26 36 AM](https://user-images.githubusercontent.com/16770170/128208953-7f0e849c-1b21-4d25-9386-742f46be70dc.png)

**Smartphone (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14
 - Browser: chrome
 - Version: 1.3.4

**Comment by narender56** [comment]
I'm still seeing this problem, how I can fix this?

<img width="940" alt="image" src="https://user-images.githubusercontent.com/8955270/176158015-c875bc57-ea77-448b-947b-0cf24656f018.png">
