### ISSUE TITLE
Custom Title Component

### ISSUE THREAD

**Issue by srivastavaanurag79** [UdaySravanK/RNSwipeButton#78]
![dc3f363f-8905-461c-8df2-a0e10b7b7150](https://user-images.githubusercontent.com/24560090/134865754-23dd7a6b-1b07-497e-a682-ad44545d62e9.gif)

Can you add a prop to add a custom title component just like you gave a prop to add a custom thumb attached a reference image and gif.
![Screenshot_1632728781](https://user-images.githubusercontent.com/24560090/134865946-50877ff6-ca3f-4e13-bd16-456de852d3f1.png)
?

**Comment by srivastavaanurag79** [comment]
I have created the second button but you already have all the output callbacks, just a custom title component would make it complete?

**Comment by ah584d** [comment]
hi i'm not sure i got you , what do you men by custom title? like on the bottom slider? i can contribute to do the change but please explain me again  - thanks

**Comment by srivastavaanurag79** [comment]
yes like the bottom slider, like you have given the option to add a custom thumb slider, can you give the option to add custom text just like the bottom slider ? that would be great.

![image](https://user-images.githubusercontent.com/24560090/134894518-b9d1a083-b066-4962-a6e3-5af751fb9134.png)

This is how I want my slider to look
