### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by chukiatt** [UdaySravanK/RNSwipeButton#79]
I am sorry

**Comment by ah584d** [comment]
you project runs with react 17.0.2 while swipe lib expect to fund in the project react ^16.8.6
As you can see in file package.json we have the block 
```
"peerDependencies": {
    "react": "^16.8.6",
    "react-native": "^0.60.5"
  },
```

while ^ (caret) symbol means "Compatible with version" - no major version update.

You 17 is not compatible with the recommended 16.
@UdaySravanK  needs to check if 17 still continue to work with swipe lib, and then change the syntax from '^16.8.6' to' >= 16.8.6'

**Comment by chukiatt** [comment]
Is Possible to work with react 17 on the future release.

**Comment by ah584d** [comment]
please format your last response it is ugly :-(

**Comment by HarveyNgo** [comment]
> 
So did this issue get fix, because I'm using react 17 and can not downgrade to use 16.8.6

**Comment by ah584d** [comment]
I will start working on it - just pointing out your message now...

**Comment by UdaySravanK** [comment]
Now RNSwipeButton supports React 17.
