### ISSUE TITLE
Shimmer effect/Skeleton loading animation on the background

### ISSUE THREAD

**Issue by shettayyy** [UdaySravanK/RNSwipeButton#82]
Amazing library!

**Is your feature request related to a problem? Please describe.**
I would like to add a shimmer effect/skeleton loading animation that keeps infinitely running in the background indicating the user to swipe right.

**Describe the solution you'd like**
Possibility to add a child component which will be rendered as background. Using the LinearGradient component, I can show an animation running in the background.

**Describe alternatives you've considered**
At the moment, animating the background doesn't seem to be an option. I can't find any alternatives.

**Additional context**
https://www.npmjs.com/package/react-native-shimmer

The example in the above library provides a demo of what's expected. But, instead of text, the animation happens in the background.

**Comment by UdaySravanK** [comment]
Thanks @shettayyy 
Created a TODO item in the project as a feature work, please find it on [the board](https://github.com/UdaySravanK/RNSwipeButton/projects/1#card-82177716)

**Comment by shameem-upay** [comment]
Hi @UdaySravanK 
We are waiting to see this new feature in this package

**Comment by UdaySravanK** [comment]
Hi, I can understand the importance of of requirement but I may not be able to work in this any soon. If somebody can contribute, please pick up the Todo task. Thanks
