### ISSUE TITLE
Custom Title component

### ISSUE THREAD

**Issue by hetmann** [UdaySravanK/RNSwipeButton#94]
**Is your feature request related to a problem? Please describe.**
- add support for `custom title component`

**Describe the solution you'd like**
```jsx
titleComponent={<View><Text>Custom</Text><Image source={} /><View>}
```

**Describe alternatives you've considered**
- n/a

**Additional context**
This will help users to use a custom component like a Text + Icon/Image

**Comment by ah584d** [comment]
can you add please a picture as an example , just to be sure that I understand what would you need? thanks

**Comment by mayying** [comment]
i want to add numberOfLines to custom text component too. but seems like it's not doable now.
